[package]
name = "big_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
task_scheduler_lib = {path="task_scheduler"}
